/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package casarural;

import java.awt.Image;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Pedro
 */
public class U2_T2_Casas extends javax.swing.JFrame {

    Calendar hoy=Calendar.getInstance();
    Calendar enUnAño=Calendar.getInstance();
    Date fechaHoy, fechaUnAño;
    
    
    public U2_T2_Casas() {
        initComponents();
        //Cambia el fondo al color elegido de el primer JFrame
        getContentPane().setBackground(ColorManager.getColor());
        //Cambia el logo de la ventana
        logo();
        //Aqui oculto cuando se abra la ventana, la opcion de regimen de alojamiento y la edad de los niños, 
        //porque esto solo quiero que aparezca cuando el usuario seleccione la opcion correspondiente a estos campos
        jLabel6.setVisible(false);
        jComboBox2.setVisible(false);
        jLabel9.setVisible(false);
        jLabel10.setVisible(false);
        jLabel11.setVisible(false);
        jLabel12.setVisible(false);
        jTextField2.setVisible(false);
        jTextField3.setVisible(false);
        jTextField4.setVisible(false);
        jTextField5.setVisible(false);
        
        hoy.set(hoy.get(Calendar.YEAR),hoy.get(Calendar.MONTH), hoy.get(Calendar.DAY_OF_MONTH)-1);
        fechaHoy=hoy.getTime();
        
        //System.out.println(hoy);
        System.out.println(fechaHoy);
        
        enUnAño.set(hoy.get(Calendar.YEAR)+1,hoy.get(Calendar.MONTH), hoy.get(Calendar.DAY_OF_MONTH));
        fechaUnAño=enUnAño.getTime();
        
        //System.out.println(enUnAño);
        System.out.println(fechaUnAño);       
    }
    
    public void logo() {    
        Image logo = new ImageIcon(getClass().getResource("coche.jpg")).getImage();
        setIconImage(logo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        jXDatePicker2 = new org.jdesktop.swingx.JXDatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Destino:");

        jTextField1.setToolTipText("Introduce el destino a donde vas");
        jTextField1.setMaximumSize(new java.awt.Dimension(100, 100));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        jCheckBox1.setToolTipText("Marca esta casilla si no sabes en que fechas viajar");
        jCheckBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox1ItemStateChanged(evt);
            }
        });
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Fecha Entrada");

        jLabel3.setText("Fecha Salida");

        jLabel4.setText("Si no sabes en que fecha viajar, marca esta casilla:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Apartamento Rural", "Casa Rural completa", "Casa Rural por Habitaciones", "Centro de Turismo Rural", "Hospedería" }));
        jComboBox1.setToolTipText("Elige un tipo de alojamiento");
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Tipos de Alojamientos:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alojamiento y Desayuno (AD)", "Media Pensión (MP)", "Pensión Completa (PC)", "Solo Alojamiento (SA)" }));
        jComboBox2.setToolTipText("Elige un regimen de alojamiento");
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Regimen de Alojamiento:");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jComboBox3.setToolTipText("Elige el numero de adultos que viajaran");

        jLabel7.setText("Numero de adultos:");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4" }));
        jComboBox4.setToolTipText("Elige el numero de niños que viajaran");
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        jLabel8.setText("Numero de niños:");

        jLabel9.setText("Edad niño 1:");

        jTextField2.setToolTipText("Introduce la edad del primer niño");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel10.setText("Edad niño 2:");

        jTextField3.setToolTipText("Introduce la edad del segundo niño");

        jLabel11.setText("Edad niño 3:");

        jTextField4.setToolTipText("Introduce la edad del tercer niño");

        jLabel12.setText("Edad niño 4:");

        jTextField5.setToolTipText("Introduce la edad del cuarto niño");
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jButton1.setText("Resumen");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/casarural/login.png"))); // NOI18N
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(30, 30, 30)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(82, 82, 82))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jCheckBox1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jXDatePicker2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                            .addComponent(jTextField3)
                            .addComponent(jTextField4)
                            .addComponent(jTextField5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(25, 25, 25))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jXDatePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jXDatePicker2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // Restringe la cantidad de palabras en el textfield de destino
        if(jTextField1.getText().length()>=100)
        {
            jTextField1.setText(jTextField1.getText().substring(0, 4));
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // Si el usuario marca el checkbox
        if (jCheckBox1.isSelected()){
            jCheckBox1.setText("Se le enviarán al correo las mejores fechas");
        }
        else{
            jCheckBox1.setText("");
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ItemStateChanged

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // Si el usuario elige en el tipo de alojamiento una de esas dos opciones:
        String opcionSeleccionada = (String) jComboBox1.getSelectedItem(); // Obtiene la opción seleccionada
        if (opcionSeleccionada.equals("Casa Rural por Habitaciones") || opcionSeleccionada.equals("Hospedería")){
            //Se mostrara el otro comboBox de regimen de alojamiento
            jComboBox2.setVisible(true);
            jLabel6.setVisible(true);
            jLabel6.setText("Régimen de Alojamiento:");
        }
        else{
            //Si el usuario vuelve a cambiar a otra opcion que no sea "Casa Rural por Habitaciones" || "Hospedería", 
            //vuelve a ocultar el comboBox regimen de alojamiento
            jComboBox2.setVisible(false);
            jLabel6.setText("");
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // Esto basicamente hara que cuando el usuario vaya eligiendo la cantidad de niños, 
        //mostrara o ocultara la cantidad de campos que saldran para poner las edades de los niños
        int opcionSeleccionada = (int) jComboBox4.getSelectedIndex();
        switch (opcionSeleccionada) {
        case 1 -> {
            jLabel9.setVisible(true);
            jTextField2.setVisible(true);
            jLabel10.setVisible(false);
            jLabel11.setVisible(false);
            jLabel12.setVisible(false);
            jTextField3.setVisible(false);
            jTextField4.setVisible(false);
            jTextField5.setVisible(false);
            }
        case 2 -> {
            jLabel9.setVisible(true);
            jLabel10.setVisible(true);
            jTextField2.setVisible(true);
            jTextField3.setVisible(true);
            jLabel11.setVisible(false);
            jLabel12.setVisible(false);
            jTextField4.setVisible(false);
            jTextField5.setVisible(false);
            }
        case 3 -> {
            jLabel9.setVisible(true);
            jLabel10.setVisible(true);
            jLabel11.setVisible(true);
            jTextField2.setVisible(true);
            jTextField3.setVisible(true);
            jTextField4.setVisible(true);
            jLabel12.setVisible(false);
            jTextField5.setVisible(false);
            }
        case 4 -> {
            jLabel9.setVisible(true);
            jLabel10.setVisible(true);
            jLabel11.setVisible(true);
            jLabel12.setVisible(true);
            jTextField2.setVisible(true);
            jTextField3.setVisible(true);
            jTextField4.setVisible(true);
            jTextField5.setVisible(true);
            }
        default -> {
            jLabel9.setVisible(false);
            jLabel10.setVisible(false);
            jLabel11.setVisible(false);
            jLabel12.setVisible(false);
            jTextField2.setVisible(false);
            jTextField3.setVisible(false);
            jTextField4.setVisible(false);
            jTextField5.setVisible(false);
            }
        }
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Aqui muestro al usuario un JOptionPane cuando le da al boton de buscar, si acepta le mandara al resumen y si le da a que no, 
        //volvera a esta misma ventana
        int opcionJPane = JOptionPane.showConfirmDialog(null, "¿Quieres continuar con los datos proporcionados?", "¿Seguro?", JOptionPane.YES_NO_OPTION); 
        if (opcionJPane == JOptionPane.YES_OPTION) {
            //Fechas
            Boolean continuar=true;
            System.out.println(jXDatePicker1.getDate());
            System.out.println(jXDatePicker2.getDate());
            if ((jXDatePicker1.getDate()!=null) && (jXDatePicker2.getDate()!=null)){
                if(jXDatePicker1.getDate().before(fechaHoy) || jXDatePicker1.getDate().after(fechaUnAño)){            
                    JOptionPane.showMessageDialog(this, "Fecha1 menor a la actual o superior a un año");  
                    continuar=false;
                }else if (jXDatePicker2.getDate().before(fechaHoy) || jXDatePicker2.getDate().after(fechaUnAño)){            
                    JOptionPane.showMessageDialog(this, "Fecha2 menor a la actual o superior a un año");  
                    continuar=false;
                }else if (jXDatePicker1.getDate().after(jXDatePicker2.getDate())){            
                    JOptionPane.showMessageDialog(this, "Fecha1 mayor a fecha2");  
                    continuar=false;     
                }else{
                    JOptionPane.showMessageDialog(this, "Fecha correcta"); 
                    continuar=true;
                }
            }else{
                   //JOptionPane.showMessageDialog(this, "Faltan fechas");  
                   continuar=true;
            }

            if (continuar == true){
                U2_T2_ResumenDatos ventanaResumen = new U2_T2_ResumenDatos();
                ventanaResumen.setVisible(true);

                //Resumen fechas
                //Si la opcion de no sabes en que fecha viajar NO esta seleccionada, pondra en el resumen las fechas
                if (!jCheckBox1.isSelected()){
                    Date fechaEntrada = jXDatePicker1.getDate();
                    DateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
                    String strDate = dateFormat.format(fechaEntrada);
                    ventanaResumen.jTextField10.setText(strDate);

                    Date fechaSalida = jXDatePicker2.getDate();
                    DateFormat dateFormat1 = new SimpleDateFormat("dd-MM-yyyy");
                    String strDate1 = dateFormat1.format(fechaSalida);
                    ventanaResumen.jTextField11.setText(strDate1);
                }


                //Esta variable la utilizare en la linea 530 para saber si la opccion seleccionada es ""Casa Rural por Habitaciones"" || ""Hospedería"",
                //entonces en el resumen se rellenara el dato de regimen de alojamiento
                String opcionSeleccionadaTipoAlojamiento = (String) jComboBox1.getSelectedItem();
                //Coloca en resumen el destino
                String destino = jTextField1.getText();
                ventanaResumen.jTextField1.setText(destino);
                //Coloca en resumen la opcion selecciona en tipo de alojamiento
                String tipoAlojamiento = (String) jComboBox1.getSelectedItem();
                ventanaResumen.jTextField2.setText(tipoAlojamiento);
                //Variable que utilizara tambien en el if de abajo
                String regimenAlojamiento = (String) jComboBox2.getSelectedItem();

               
                if (opcionSeleccionadaTipoAlojamiento.equals("Casa Rural por Habitaciones") || opcionSeleccionadaTipoAlojamiento.equals("Hospedería")){
                    ventanaResumen.jTextField3.setText(regimenAlojamiento);
                }
                else{
                    ventanaResumen.jTextField3.setText("No disponible con este tipo de Alojamiento");
                }

                //Mostrar en el resumen jcombobox3 y jcombobox4
                String numeroAdultos = (String) jComboBox3.getSelectedItem();
                String numeroNiños = (String) jComboBox4.getSelectedItem();
                try {
                    // Intenta convertir la cadena a un número entero
                    int valorSeleccionadoAdultos = Integer.parseInt(numeroAdultos);
                    int valorSeleccionadoNiños = Integer.parseInt(numeroNiños);

                    // Establece el número en el JTextField
                    ventanaResumen.jTextField4.setText(String.valueOf(valorSeleccionadoAdultos));
                    ventanaResumen.jTextField5.setText(String.valueOf(valorSeleccionadoNiños));
                    int opcionSeleccionada = (int) jComboBox4.getSelectedIndex();
                    switch (opcionSeleccionada){
                        case 1 -> {
                            String edadNiño1 = (String) jTextField2.getText();
                            ventanaResumen.jTextField6.setText(edadNiño1);
                        }
                        case 2 -> {
                            String edadNiño1 = (String) jTextField2.getText();
                            ventanaResumen.jTextField6.setText(edadNiño1);
                            String edadNiño2 = (String) jTextField3.getText();
                            ventanaResumen.jTextField7.setText(edadNiño2);
                        }
                        case 3 -> {
                            String edadNiño1 = (String) jTextField2.getText();
                            ventanaResumen.jTextField6.setText(edadNiño1);
                            String edadNiño2 = (String) jTextField3.getText();
                            ventanaResumen.jTextField7.setText(edadNiño2);
                            String edadNiño3 = (String) jTextField4.getText();
                            ventanaResumen.jTextField8.setText(edadNiño3);
                        }
                        case 4 -> {
                            String edadNiño1 = (String) jTextField2.getText();
                            ventanaResumen.jTextField6.setText(edadNiño1);
                            String edadNiño2 = (String) jTextField3.getText();
                            ventanaResumen.jTextField7.setText(edadNiño2);
                            String edadNiño3 = (String) jTextField4.getText();
                            ventanaResumen.jTextField8.setText(edadNiño3);
                            String edadNiño4 = (String) jTextField5.getText();
                            ventanaResumen.jTextField9.setText(edadNiño4);
                        }
                    }
                } catch (NumberFormatException e) {
                    // Maneja la excepción si la cadena no puede ser convertida a un número entero
                    System.out.println("Error: No se pudo convertir la cadena a un número entero.");
                }

                //Aqui voy a hacer la parte donde si el usuario marca la opcion de "no sabe que fecha viajar", 
                //ocultare las fechas de inicio y salida en el resumen y marcare el checkbox de fecha indefinida en el resumen
                if (jCheckBox1.isSelected()){
                    ventanaResumen.jCheckBox1.setSelected(true);
                    ventanaResumen.jTextField10.setText("");
                    ventanaResumen.jTextField11.setText("");
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        U2_T2_LogBBDD logVentana = new U2_T2_LogBBDD();
        logVentana.setVisible(true);
    }//GEN-LAST:event_jLabel15MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(U2_T2_Casas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(U2_T2_Casas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(U2_T2_Casas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(U2_T2_Casas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new U2_T2_Casas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker2;
    // End of variables declaration//GEN-END:variables
}
